---
- name: Collect IPs from frontend and backend and update terraform_inventory.ini
  hosts: localhost
  gather_facts: no
  tasks:

    # Step 1: Extract IP addresses from frontend.yml
    - name: Load frontend hosts from frontend.yml
      include_vars:
        file: frontend.yml
        name: frontend_hosts

    - name: Extract IPs from frontend.yml
      set_fact:
        frontend_ips: "{{ frontend_hosts.hosts | map(attribute='ansible_host') | list }}"

    # Step 2: Extract IP addresses from backend.yml
    - name: Load backend hosts from backend.yml
      include_vars:
        file: backend.yml
        name: backend_hosts

    - name: Extract IPs from backend.yml
      set_fact:
        backend_ips: "{{ backend_hosts.hosts | map(attribute='ansible_host') | list }}"

    # Step 3: Write the IPs into terraform_inventory.ini

    # Write the frontend IPs
    - name: Add frontend IPs to terraform_inventory.ini
      ini_file:
        path: terraform_inventory.ini
        section: frontend
        option: "{{ item }}"
        value: ""
        create: yes
      with_items: "{{ frontend_ips }}"
      notify:
        - Update terraform_inventory.ini

    # Write the backend IPs
    - name: Add backend IPs to terraform_inventory.ini
      ini_file:
        path: terraform_inventory.ini
        section: backend
        option: "{{ item }}"
        value: ""
        create: yes
      with_items: "{{ backend_ips }}"
      notify:
        - Update terraform_inventory.ini

  handlers:
    - name: Update terraform_inventory.ini
      debug:
        msg: "terraform_inventory.ini file updated successfully!"
